version: '3.8'
services:
  local-ai:
    image: localai/localai:latest-aio-cpu
    command: --models-path /models --p2p
     --context-size 2048 --threads 9 --localai-config-dir /configuration
    environment:
      - DEBUG=true
    volumes:
      - ./models:/models
      - ./tmp/generated/images:/tmp/generated/images
      - ./configuration:/configuration
    ports:
      - 8080:8080


    restart: unless-stopped

  helper-bot:
    build: .
    depends_on:
      - local-ai
    ports:
      - 8085:8085
    environment:
  #    - AI_ENDPOINT=http://local-ai:8080/v1/chat/completions
      - AI_BASEURL=http://local-ai:8080
      - AI_ENDPOINT=http://local-ai:8080
    restart: unless-stopped
