version: '3.8'
services:
  local-ai-worker:
    image: localai/localai:latest-aio-cpu
    command: --models-path /models 
     --context-size 2048  --threads 9 --localai-config-dir /configuration worker p2p-llama-cpp-rpc --token ${P2PTOKEN}
    environment:
      - DEBUG=true
    volumes:
      - ./models:/models
      - ./tmp/generated/images:/tmp/generated/images
      - ./configuration:/configuration
    ports:
      - 8080:8080


    restart: unless-stopped


